# Generated by Django 4.1 on 2022-08-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_desc_remove_book_image_alter_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
